Issue #210 & #211 - Add MSVC `cl` job to GitHub action workflow file, and fix MSVC cl break for variadic functions (#212)
Closes #210, Closes #211

* Initial attempt to add MSVC cl job to dev-platforms.yml (renamed from os.yml)

* Restoring name of os.yml because GitHub is fighting me

* Trying to addrss job failure by setting arch:

Error: setup-msvc-dev did nothing. Please configure at least one of 'arch', 'exportVCVarsall', or 'exportVS'.

* Experimenting with declaring a FORMAT_PRINTF macro for gcc and clang, but not for MSVC cl... Also will test if we no longer need pragmas to ignore -Wsuggest-attribute=format

Co-authored-by: Copilot <copilot@github.com>

* Changed path of compiled executable for MSVC cl job to try to resolve link error:

LINK : fatal error LNK1104: cannot open file 'Release\planarity.exe'

* Path stuff is super annoying

* Restoring full os.yml jobs list, as well as trying to make MSVC cl build step more legible

* Trying to refine conditions under which we apply the format attribute

* Multiline commands: the bane of any developer's existence, and of course Windows has to be precious

* One more try before I restore MSVC cl build
command to being on one line

* Removing unsupported platforms (i.e. ARM and ARM64, as well as cross-compilation to those platforms)

* This seems to resolve the MSVC cl build failure, as well as allows us to remove the pragmas to ignore -Wsuggest-attribute=format for gcc

* Renaming workflow to more accurately reflect work done by jobs

* If the compiler is MSVC cl (or any compiler that is not gcc nor clang and doesn't have macro __has_attribute defiled), then don't apply the format attribute. If the compiler has the __attribute__ keyword (or, explicitly calling out gcc and clang versions where the __has_attribute macro may not be defined), then use gnu_printf archetype for gcc and use the printf archetype otherwise.

---------

Co-authored-by: Copilot <copilot@github.com>